# This is a basic workflow to help you get started with Actions

name: Update

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: npm install
        run: |
          cd ./scripts
          npm install
          cd ..

      - name: update teams
        run: |
          node ./scripts/updateTeams.js "./teams" ${{ secrets.GH_TOKEN }}

      - name: update labels
        run: |
          node ./scripts/updateLabels.js "./teams" ${{ secrets.GH_TOKEN }}

